name: CI/CD back

on:
  push:
    branches:
      - "back"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Back
        uses: izemaghilas/platformsh-nodejs-deploy-action@v1.1
        with:
          project-id: ${{ secrets.PLATFORM_PROJECT_ID }}
          cli-token: ${{ secrets.PLATFORM_API_TOKEN }}
          force-push: true
          environment-name: main
