name: CI/CD back

on:
  push:
    branches:
      - "main"
      - "feat/ci-cd"
    paths:
      - "back/**"
      - ".github/workflows/back.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: izemaghilas/platformsh-nodejs-deploy-action@v1.1
        with:
          project-id: ${{ secrets.PLATFORM_PROJECT_ID }}
          cli-token: ${{ secrets.PLATFORM_API_TOKEN }}
          force-push: true
          environment-name: main
