name: CI/CD front

on:
  push:
    branches:
      - "front"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Front
        uses: izemaghilas/platformsh-nodejs-deploy-action@v1.1
        with:
          project-id: ${{ secrets.FRONT_PLATFORM_PROJECT_ID }}
          cli-token: ${{ secrets.FRONT_PLATFORM_API_TOKEN }}
          force-push: true
          environment-name: main
